# Join Datasets

In [1]:
import pandas as pd
import numpy as np

In [16]:
austin = pd.read_csv('clean-data/listings_detailed_clean_austin.csv')
nashville = pd.read_csv('clean-data/listings_detailed_clean_nashville.csv')
nola = pd.read_csv('clean-data/listings_detailed_clean_neworleans.csv')
denver = pd.read_csv('clean-data/listings_detailed_clean_denver.csv')
chicago = pd.read_csv('clean-data/listings_detailed_clean_chicago.csv')

In [17]:
nola.isnull().sum()

id                                   0
host_id                              0
host_name                            0
host_since                           0
host_location                        0
host_response_time                1154
host_response_rate                1154
host_acceptance_rate               976
host_is_superhost                    0
host_listings_count                  0
host_total_listings_count            0
host_verifications                   6
host_has_profile_pic                 0
host_identity_verified               0
neighbourhood_cleansed               0
latitude                             0
longitude                            0
room_type                            0
accommodates                         0
bathrooms_text                       0
bedrooms                             0
beds                                 0
amenities                            0
price                                0
number_of_reviews                    0
review_scores_value                883
calculated_host_listings_count       0
num_bath                             0
city                                 0
amenities_count                      0
dtype: int64

In [26]:
nola.loc[nola['host_verifications'].isnull(), ['host_verifications']]

     host_verifications
1671                NaN
4337                NaN
4653                NaN
5934                NaN
5937                NaN
5960                NaN

In [4]:
combined_df = pd.concat([austin, nashville, nola, denver, chicago], ignore_index=True)

In [5]:
combined_df

,id,host_id,host_name,host_since,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_listings_count,...,bedrooms,beds,amenities,price,number_of_reviews,review_scores_value,calculated_host_listings_count,num_bath,city,amenities_count
0,5456,8028,Sylvia,2009-02-16,"Austin, TX",within an hour,100%,95%,t,2.0,...,1.0,2.0,"[""Heating"", ""Backyard"", ""Bed linens"", ""Hot wat...",176.0,630,4.79,2,1.0,Austin,27
1,5769,8186,Elizabeth,2009-02-19,"Austin, TX",within a few hours,100%,95%,t,1.0,...,1.0,1.0,"[""Private backyard"", ""Free parking on premises...",42.0,275,4.92,1,1.0,Austin,36
2,6413,13879,Todd,2009-04-17,"Austin, TX",NaN,NaN,100%,t,1.0,...,1.0,1.0,"[""Heating"", ""Outdoor dining area"", ""Dove body ...",109.0,122,4.93,1,1.0,Austin,48
3,6448,14156,Amy,2009-04-20,"Austin, TX",within an hour,100%,100%,t,1.0,...,1.0,2.0,"[""Pack \u2019n play/Travel crib"", ""Free parkin...",240.0,295,4.90,1,1.0,Austin,61
4,8502,25298,Karen,2009-07-11,"Austin, TX",within a day,60%,70%,f,1.0,...,1.0,1.0,"[""Essentials"", ""Heating"", ""Central air conditi...",85.0,48,4.57,1,1.0,Austin,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43062,25879,101521,Red,2010-03-31,"Chicago, IL",within a few hours,100%,75%,f,8.0,...,2.0,3.0,"[""Self check-in"", ""Dedicated workspace"", ""Oven...",86.0,51,4.35,3,1.0,Chicago,40
43063,28749,27506,Lauri,2009-07-25,Italy,within a few hours,100%,85%,t,1.0,...,3.0,3.0,"[""Self check-in"", ""Oven"", ""Baking sheet"", ""Fir...",157.0,169,4.67,1,2.0,Chicago,44
43064,37738,162364,Mat And Randy,2010-07-09,"Chicago, IL",NaN,NaN,NaN,f,2.0,...,1.0,1.0,"[""Self check-in"", ""Dedicated workspace"", ""Oven...",110.0,250,4.98,2,1.5,Chicago,40
43065,71930,334241,Michael And Veronica,2011-01-03,"Chicago, IL",within an hour,90%,97%,t,2.0,...,1.0,1.0,"[""Laundromat nearby"", ""Dedicated workspace"", ""...",84.0,101,4.80,2,1.0,Chicago,43
43066,84042,334241,Michael And Veronica,2011-01-03,"Chicago, IL",within an hour,90%,97%,t,2.0,...,1.0,1.0,"[""Dedicated workspace"", ""Oven"", ""Baking sheet""...",89.0,124,4.86,2,1.0,Chicago,36

In [31]:
# Replace '[]' with None in 'host_verifications' column
combined_df['host_verifications'] = combined_df['host_verifications'].fillna("None")

In [32]:
combined_df.isnull().sum()

id                                   0
host_id                              0
host_name                            2
host_since                           0
host_location                        0
host_response_time                7421
host_response_rate                7421
host_acceptance_rate              5974
host_is_superhost                    0
host_listings_count                  0
host_total_listings_count            0
host_verifications                   0
host_has_profile_pic                 0
host_identity_verified               0
neighbourhood_cleansed               0
latitude                             0
longitude                            0
room_type                            0
accommodates                         0
bathrooms_text                       0
bedrooms                             0
beds                                 0
amenities                            0
price                                0
number_of_reviews                    0
review_scores_value               7652
calculated_host_listings_count       0
num_bath                             0
city                                 0
amenities_count                      0
dtype: int64

In [36]:
# change column name
combined_df.rename(columns={'neighbourhood_cleansed': 'neighborhood'}, inplace=True)

# Verify the change by printing the DataFrame columns
print(combined_df.columns)

Index(['id', 'host_id', 'host_name', 'host_since', 'host_location',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_listings_count', 'host_total_listings_count',
       'host_verifications', 'host_has_profile_pic', 'host_identity_verified',
       'neighborhood', 'latitude', 'longitude', 'room_type', 'accommodates',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'number_of_reviews', 'review_scores_value',
       'calculated_host_listings_count', 'num_bath', 'city',
       'amenities_count'],
      dtype='object')

In [37]:
combined_df

,id,host_id,host_name,host_since,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_listings_count,...,bedrooms,beds,amenities,price,number_of_reviews,review_scores_value,calculated_host_listings_count,num_bath,city,amenities_count
0,5456,8028,Sylvia,2009-02-16,"Austin, TX",within an hour,100%,95%,t,2.0,...,1.0,2.0,"[""Heating"", ""Backyard"", ""Bed linens"", ""Hot wat...",176.0,630,4.79,2,1.0,Austin,27
1,5769,8186,Elizabeth,2009-02-19,"Austin, TX",within a few hours,100%,95%,t,1.0,...,1.0,1.0,"[""Private backyard"", ""Free parking on premises...",42.0,275,4.92,1,1.0,Austin,36
2,6413,13879,Todd,2009-04-17,"Austin, TX",NaN,NaN,100%,t,1.0,...,1.0,1.0,"[""Heating"", ""Outdoor dining area"", ""Dove body ...",109.0,122,4.93,1,1.0,Austin,48
3,6448,14156,Amy,2009-04-20,"Austin, TX",within an hour,100%,100%,t,1.0,...,1.0,2.0,"[""Pack \u2019n play/Travel crib"", ""Free parkin...",240.0,295,4.90,1,1.0,Austin,61
4,8502,25298,Karen,2009-07-11,"Austin, TX",within a day,60%,70%,f,1.0,...,1.0,1.0,"[""Essentials"", ""Heating"", ""Central air conditi...",85.0,48,4.57,1,1.0,Austin,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43062,25879,101521,Red,2010-03-31,"Chicago, IL",within a few hours,100%,75%,f,8.0,...,2.0,3.0,"[""Self check-in"", ""Dedicated workspace"", ""Oven...",86.0,51,4.35,3,1.0,Chicago,40
43063,28749,27506,Lauri,2009-07-25,Italy,within a few hours,100%,85%,t,1.0,...,3.0,3.0,"[""Self check-in"", ""Oven"", ""Baking sheet"", ""Fir...",157.0,169,4.67,1,2.0,Chicago,44
43064,37738,162364,Mat And Randy,2010-07-09,"Chicago, IL",NaN,NaN,NaN,f,2.0,...,1.0,1.0,"[""Self check-in"", ""Dedicated workspace"", ""Oven...",110.0,250,4.98,2,1.5,Chicago,40
43065,71930,334241,Michael And Veronica,2011-01-03,"Chicago, IL",within an hour,90%,97%,t,2.0,...,1.0,1.0,"[""Laundromat nearby"", ""Dedicated workspace"", ""...",84.0,101,4.80,2,1.0,Chicago,43
43066,84042,334241,Michael And Veronica,2011-01-03,"Chicago, IL",within an hour,90%,97%,t,2.0,...,1.0,1.0,"[""Dedicated workspace"", ""Oven"", ""Baking sheet""...",89.0,124,4.86,2,1.0,Chicago,36

In [38]:
# Save as a new csv file
combined_df.to_csv('clean-data/listings_detailed_clean_central.csv', index=False)

# Host with multiple properties in different cities

In [44]:
# Step 1: Ensure the 'city' column exists and is accurate (it seems you've already done this).

# Step 2: Group by 'host_id' and aggregate unique cities for each host
hosts_cities = combined_df.groupby('host_id')['city'].unique()

# Step 3: Identify hosts with listings in more than one city
hosts_multiple_cities = hosts_cities[hosts_cities.apply(len) > 1]

# Step 4: For a more detailed view, filter the original DataFrame for these hosts
# and perhaps sort by 'host_id' and 'city' for better readability
detailed_listings = combined_df[combined_df['host_id'].isin(hosts_multiple_cities.index)].sort_values(by=['host_id', 'city'])

# Optionally, to just see the host_id, listing id (assuming 'id' is your listing identifier), and city:
listings_by_city = detailed_listings[['host_id', 'host_name', 'id', 'city']]

print(listings_by_city)

         host_id  host_name                  id         city
6061        5146      Jorge            43274463       Austin
26191       5146      Jorge            40972438  New Orleans
26276       5146      Jorge            16315680  New Orleans
28943       5146      Jorge            16031419  New Orleans
29620       5146      Jorge             2109038  New Orleans
...          ...        ...                 ...          ...
21815  483060689  Mirabilis  760203399156064148    Nashville
22726  483060689  Mirabilis  841442176538495904    Nashville
22727  483060689  Mirabilis  841464379007949066    Nashville
42030  486139080        Vax  751742096611773345      Chicago
21927  486139080        Vax  762648408598042832    Nashville

[2532 rows x 4 columns]

In [45]:
combined_df[combined_df['host_id'] ==5146]

,id,host_id,host_name,host_since,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_listings_count,...,bedrooms,beds,amenities,price,number_of_reviews,review_scores_value,calculated_host_listings_count,num_bath,city,amenities_count
6061,43274463,5146,Jorge,2008-12-13,"San Antonio, TX",within an hour,100%,96%,t,50.0,...,1.0,2.0,"[""Outdoor kitchen"", ""Heating"", ""Outdoor dining...",300.0,0,NaN,1,1.0,Austin,51
26191,40972438,5146,Jorge,2008-12-13,"San Antonio, TX",within an hour,100%,97%,t,50.0,...,1.0,2.0,"[""Smoke alarm"", ""Refrigerator"", ""Coffee maker""...",225.0,1,5.0,6,1.0,New Orleans,44
26276,16315680,5146,Jorge,2008-12-13,"San Antonio, TX",within an hour,100%,97%,t,50.0,...,1.0,2.0,"[""Smoke alarm"", ""Refrigerator"", ""Patio or balc...",200.0,3,5.0,6,1.0,New Orleans,38
28943,16031419,5146,Jorge,2008-12-13,"San Antonio, TX",within an hour,100%,97%,t,50.0,...,1.0,1.0,"[""Smoke alarm"", ""Refrigerator"", ""Coffee maker""...",240.0,3,5.0,6,1.0,New Orleans,29
29620,2109038,5146,Jorge,2008-12-13,"San Antonio, TX",within an hour,100%,97%,t,50.0,...,1.0,1.0,"[""Smoke alarm"", ""Refrigerator"", ""Coffee maker""...",240.0,5,4.5,6,1.0,New Orleans,47
29621,2123907,5146,Jorge,2008-12-13,"San Antonio, TX",within an hour,100%,97%,t,50.0,...,1.0,2.0,"[""Smoke alarm"", ""Refrigerator"", ""Coffee maker""...",225.0,4,5.0,6,1.0,New Orleans,42
29745,16406089,5146,Jorge,2008-12-13,"San Antonio, TX",within an hour,100%,97%,t,50.0,...,1.0,2.0,"[""Smoke alarm"", ""Refrigerator"", ""Coffee maker""...",205.0,1,4.0,6,1.0,New Orleans,40

# 0 Reviews

In [39]:
combined_df[combined_df['number_of_reviews'] == 0]

,id,host_id,host_name,host_since,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_listings_count,...,bedrooms,beds,amenities,price,number_of_reviews,review_scores_value,calculated_host_listings_count,num_bath,city,amenities_count
9,23496,8028,Sylvia,2009-02-16,"Austin, TX",within an hour,100%,95%,t,2.0,...,3.0,4.0,"[""Pantene conditioner"", ""Free parking on premi...",200.0,0,NaN,2,1.0,Austin,31
27,77347,382265,Leslie,2011-02-08,"Austin, TX",NaN,NaN,NaN,f,1.0,...,1.0,1.0,"[""Free parking on premises"", ""Heating"", ""Backy...",104.0,0,NaN,1,1.0,Austin,41
84,314152,1614097,Denise,2012-01-16,"Austin, TX",NaN,NaN,NaN,f,1.0,...,2.0,2.0,[],350.0,0,NaN,1,2.0,Austin,0
99,331549,1690383,Sandra,2012-02-02,"Austin, TX",NaN,NaN,NaN,f,1.0,...,1.0,1.0,"[""Washer"", ""Free parking on premises"", ""Heatin...",100.0,0,NaN,1,1.0,Austin,8
123,351865,1782559,Julie,2012-02-20,"Austin, TX",NaN,NaN,NaN,f,1.0,...,1.0,1.0,"[""Free parking on premises"", ""Heating"", ""Break...",75.0,0,NaN,1,1.0,Austin,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42966,848982732370093638,107434423,Blueground,2016-12-16,"New York, NY",within an hour,100%,97%,f,4807.0,...,1.0,1.0,"[""Self check-in"", ""Oven"", ""Private entrance"", ...",95.0,0,NaN,658,1.0,Chicago,29
42967,849181288802249186,31669178,Donna,2015-04-21,"Chicago, IL",within an hour,100%,69%,t,14.0,...,2.0,2.0,"[""Washer"", ""Kitchen"", ""TV"", ""Wifi""]",107.0,0,NaN,13,1.0,Chicago,4
42968,849355136099814004,165881852,Jacob,2018-01-04,"Chicago, IL",NaN,NaN,NaN,f,1.0,...,1.0,1.0,"[""Public or shared beach access"", ""Dedicated w...",240.0,0,NaN,1,1.0,Chicago,51
42969,849539062724535549,100179,Kenneth,2010-03-28,"Chicago, IL",within an hour,90%,100%,f,11.0,...,1.0,1.0,"[""Self check-in"", ""Dedicated workspace"", ""Cook...",95.0,0,NaN,4,1.0,Chicago,42
43037,1417110,7622794,Leah,2013-07-21,"Chicago, IL",NaN,NaN,100%,f,1.0,...,2.0,2.0,"[""Dedicated workspace"", ""Baking sheet"", ""Outdo...",100.0,0,NaN,1,1.0,Chicago,35